### ISSUE TITLE
Tab completion for barrelname

### ISSUE THREAD

**Issue by Tincc** [shantek/PostOffice#10]
Currently on 1.6.1, same goes for all other issues reported.
idk if needed but, running Paper 1.20.4

when doing `/postoffice:barrelname` it outputs a command suggestion of `/postoffice barrelname <name>`
_doing said command doesn't change custom barrel name, so good._

Then after you execute said command it says "unknown command or insufficient permissions" suggests you to do `/postoffice reload`

I mention this, as per 1.6.1 release notes "Removed the barrelname command..."

**Comment by shantek** [comment]
This has been resolved in 2.0 - Currently in development
