### ISSUE TITLE
[Bug] Hopper can remove items from pobox

### ISSUE THREAD

**Issue by MaoDoBan** [shantek/PostOffice#19]
A hopper can insert items into a pobox, what is not necessary a bug, but if I can disable this behavior via plugin config.

The bug: a hopper can remove items from any pobox.

**Comment by shantek** [comment]
This has been fixed in [ffef99](https://github.com/shantek/PostOffice/commit/ffef99d872d592e285812a5cccd91d25bb1afdb4).

Available for testing in the following [dev build](https://shantek.dev/job/PostOffice/14/)
