### ISSUE TITLE
[Bug] Explosion can destroy a pobox

### ISSUE THREAD

**Issue by MaoDoBan** [shantek/PostOffice#20]
I tested with tnt and creeper, and both destroyed the pobox.

**Comment by shantek** [comment]
This has been fixed in [2bb5ab5](https://github.com/shantek/PostOffice/commit/2bb5ab5a568de856738f5cbfc64a056b91204df2).

Available for testing in the following [dev build](https://shantek.dev/job/PostOffice/15/artifact/target/PostOffice-dev-15.jar)
