### ISSUE TITLE
[Bug] Signs on the diagonal of the horizontal plane of the pobox are blocked as pobox signs.

### ISSUE THREAD

**Issue by MaoDoBan** [shantek/PostOffice#21]
If a player tries to edit a sign in the diagonal (red wool on below image) receive the error message (if not have .create permission).

![image](https://github.com/shantek/PostOffice/assets/11332249/e0111367-6856-40fd-8040-a07d98a8c35d)

**Comment by shantek** [comment]
This will change in v2 with how the signs and barrels are handled so may stay as is for now.

Testing with the latest dev build, without op or permissions I'm able to edit signs in the following locations:
![2024-07-05_20 38 00](https://github.com/shantek/PostOffice/assets/2194582/2a5d6c04-9a33-44d2-bffa-e572fe46c269)

Ideally in v2, all signs will be directly on front of the barrel and the plugin will track the exact placement of each barrel and sign preventing issues like this.

**Comment by MaoDoBan** [comment]
> Testing with the latest dev build, without op or permissions I'm able to edit signs in the following locations: ![2024-07-05_20 38 00](https://private-user-images.githubusercontent.com/2194582/346104865-2a5d6c04-9a33-44d2-bffa-e572fe46c269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODEzNjUsIm5iZiI6MTcyMDE4MTA2NSwicGF0aCI6Ii8yMTk0NTgyLzM0NjEwNDg2NS0yYTVkNmMwNC05YTMzLTQ0ZDItYmZmYS1lNTcyZmU0NmMyNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMTIwNDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZiY2I3MDVjMWMyMDE4ZGE1Mjc4MjYxNTkwODQ1YTkzOTBhM2RmN2Q0YTA2NDhkZTQyNTM5NTg3ZmIxMjdiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fJ5H14A-Ew3sszEjLtzm055rXD8HRyUmr991mWY7ihk)

Only to clarify my report, in horizontal axis, the red signs work as pobox signs and can't be edited by "common players":
![image](https://github.com/shantek/PostOffice/assets/11332249/df15b1c2-d793-48c7-a01f-71f0c3366719)
![image](https://github.com/shantek/PostOffice/assets/11332249/4bceb873-7f63-43c6-b4be-90ef64f97520)

**Comment by shantek** [comment]
V2 currently in development now stores the sign location when setting up the post box, this resolves this issue.
