### ISSUE TITLE
[Bug] Wither can destroy a pobox

### ISSUE THREAD

**Issue by MaoDoBan** [shantek/PostOffice#23]
I tested with a wither boss, hit him next to the block, and he destroyed the pobox (I verified via coreprotect plugin).

I suspect the Ender Dragon can destroy pobox too.

**Comment by shantek** [comment]
![2024-09-21_12 00 09](https://github.com/user-attachments/assets/900d30db-1f3f-4cd3-85f2-314b18b9a5b0)
![2024-09-21_12 00 25](https://github.com/user-attachments/assets/11bd45b4-39fb-47ed-bceb-7de7ef531248)

This doesn't appear to be an issue in 2.0.
