### ISSUE TITLE
[Bug] Giant mushroom can destroy pobox sign

### ISSUE THREAD

**Issue by MaoDoBan** [shantek/PostOffice#24]
![image](https://github.com/shantek/PostOffice/assets/11332249/4588ab21-fb3a-4dcd-ade6-383618518257)

Fun fact: the pobox remains protected, workin as pobox without his sign, but the original "owner" can not interact and not receive the notification of new itens on pobox.

**Comment by shantek** [comment]
Confirmed this is still an issue in the 2.0 dev build. Needs further investigation.

**Comment by shantek** [comment]
Added a new onStructureGrow listener to listen for any protected blocks and remove them from the list while still allowing them to grow.

Added to the 2.0 dev build.

![2024-09-21_11 14 04](https://github.com/user-attachments/assets/b4843d06-6c8a-4171-bb7a-3271d09e4130)
