### ISSUE TITLE
Hot bar bug

### ISSUE THREAD

**Issue by Tincc** [shantek/PostOffice#7]
When using another players post box you can take any item from the box.

How to replicate:

1. Have a item you don't want in your offhand
2. Hover over the item you want in the members post box
3. Click F and it will switch the item in your offhand with the item in the box

**Comment by shantek** [comment]
@Tincc are you able to confirm with this, if you open their post box again is the item back in there again?

If you try to then move this item in your inventory does it disappear?

**Comment by Tincc** [comment]
Apologies for the late reply, didn't see this. The item is whatever you put into the mailbox and it stays there. When moving the item in inventory it doesn't disappear. Posted a video of the glitch in the discord.

**Comment by shantek** [comment]
Confirmed as resolved in the 2.0 dev build.
