### ISSUE TITLE
Block spam mail! [Suggestion]

### ISSUE THREAD

**Issue by Tincc** [shantek/PostOffice#9]
If possible add a way to block/stop certain people from accessing your mailbox or stop them from adding items.
I can see this being a way people will misuse the mailing system.

**Comment by shantek** [comment]
As an initial implementation, I'll look at adding a permission node that would prevent players from using the post office system. 

Possibly set up so if the banned permission node is present they can't interact with the post box at all and are shown a warning when doing so.

Also need to add this to the translation file.

**Comment by shantek** [comment]
Use permission node has been added to v2 currently in development, allowing you to "ban" users from accessing the post office system.
